language: python
python:
  - "2.7"
install:
  - pip install requests
  - pip install numpy
  - pip install pymongo
services:
  - mongodb
before_script: python videk-proxy.py
script: python proxy-client.py
