language: python
python:
  - "2.7"
node_js:
  - "4.3"
install:
  - pip install requests
  - pip install numpy
  - pip install pymongo
services:
  - mongodb
before_script:
  - git clone https://github.com/sensorlab/SensorManagementSystem.git
  - cd SensorManagementSystem/server
  - npm install
  - nodejs top.js &
  - cd ../..
  - python videk-proxy.py &
  - sleep 5
script: python videk-proxy-test.py
